name: Android CI

on:
  push:
    branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  lint:
    name: Android Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup jvm
        uses: ./.github/actions/jvm_setup

      - name: run lint
        run: ./gradlew lintJunitDebugUnitTest

  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup jvm
        uses: ./.github/actions/jvm_setup

      - name: run lint
        run: ./gradlew lintKotlin

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup jvm
        uses: ./.github/actions/jvm_setup

      - name: run unit tests
        run: ./gradlew testJunitDebugUnitTest

  instrumentation_tests:
    if: false
    name: JUnit Instrumentation Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run emulator
        uses: ./.github/actions/emulator_run
        with:
          api-level: 30
          script: ./gradlew connectedJunitDebugAndroidTest --info

  feature_tests_movielist:
    if: false
    name: Cucumber Feature Tests - MovieList
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run emulator
        uses: ./.github/actions/emulator_run
        with:
          api-level: 30
          script: ./gradlew connectedCucumberDebugAndroidTest --info -Pcucumber.tags="MovieListFeature"

  feature_tests_archive:
    if: false
    name: Cucumber Feature Tests - Archive
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run emulator
        uses: ./.github/actions/emulator_run
        with:
          api-level: 30
          script: ./gradlew connectedCucumberDebugAndroidTest --info -Pcucumber.tags="ArchiveFeature"

  feature_tests_search:
    if: false
    name: Cucumber Feature Tests - Search
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run emulator
        uses: ./.github/actions/emulator_run
        with:
          api-level: 30
          script: ./gradlew connectedCucumberDebugAndroidTest --info -Pcucumber.tags="SearchFeature"
